key_config:
  cloud_orchestrator:
    - "tosca.nodes.MiCADO.Occopus.CloudSigma.Compute"
    - "tosca.nodes.MiCADO.Occopus.Nova.Compute"
    - "tosca.nodes.MiCADO.Occopus.CloudBroker.Compute"
    - "tosca.nodes.MiCADO.Occopus.EC2.Compute"
  container_orchestrator:
    - "tosca.nodes.MiCADO.Container.Application.Docker"
  policies_engine:
    - "some policy types"
  security_enforcer:
    - "some security Enforcer"
