config:
  dry_run: True
  path_log: "/Users/greg/Desktop/work/COLA/submitter/greg_fork/component_submitter/submitter.log"

Adaptor_config:
 DummySeAdaptor:
   types:
     - "tosca.policies.Scaling.*"
   endoint: "endpoint"
   volume: "/Users/greg/Desktop/work/COLA/submitter/greg_fork/component_submitter/files/output_configs/"


 DockerAdaptor:
   types:
     - "tosca.nodes.MiCADO.Container.Application.Docker"
   endoint: "endpoint"
   volume: "/Users/greg/Desktop/work/COLA/submitter/greg_fork/component_submitter/files/output_configs/"
