<<<<<<< HEAD
main_config:
  dry_run: True
=======
config:
  dry_run: False
>>>>>>> 8601ecd3cee3965393856c74caa502b5b304b3a8
  #path_log: "/var/lib/toscasubmitter/submitter.log"
  path_log: "submitter.log"
step:
  translate:
    - SecurityEnforcerAdaptor
    - DockerAdaptor
    - OccopusAdaptor
    - PkAdaptor
  execute:
    - DockerAdaptor
    - SecurityEnforcerAdaptor
    - OccopusAdaptor
    - PkAdaptor
  update:
    - DockerAdaptor
    - SecurityEnforcerAdaptor
    - OccopusAdaptor
    - PkAdaptor
  undeploy:
    - SecurityEnforcerAdaptor
    - DockerAdaptor
    - OccopusAdaptor
    - PkAdaptor
  cleanup:
    - DockerAdaptor
    - SecurityEnforcerAdaptor
    - OccopusAdaptor
    - PkAdaptor

adaptor_config:
 SecurityEnforcerAdaptor:
   types:
     - "tosca.policies.Scaling.*"
   endoint: "endpoint"
   volume: "/var/lib/submitter/security_workdir_example/"
<<<<<<< HEAD
=======

>>>>>>> 8601ecd3cee3965393856c74caa502b5b304b3a8
 DockerAdaptor:
   types:
     - "tosca.nodes.MiCADO.Container.Application.Docker"
   endoint: "endpoint"
<<<<<<< HEAD

=======
>>>>>>> 8601ecd3cee3965393856c74caa502b5b304b3a8
   volume: "/var/lib/submitter/files/output_configs/"


 OccopusAdaptor:
   types:
     - "tosca.nodes.MiCADO.Occopus.*"
   endoint: "endpoint"
   volume: "/var/lib/submitter/files/output_configs/"


 PkAdaptor:
   types:
     - "tosca.policies.Scaling.MiCADO"
   endpoint: "policykeeper:12345"
   volume: "/var/lib/submitter/files/output_configs/"
