main_config:
  dry_run: True
  path_log: "/Users/greg/Desktop/work/COLA/submitter/greg_fork/component_submitter/submitter.log"

step:
  translate:
    - SecurityEnforcerAdaptor
    - DockerAdaptor
  execute:
    - DockerAdaptor
    - SecurityEnforcerAdaptor
  update:
    - DockerAdaptor
    - SecurityEnforcerAdaptor
  undeploy:
    - SecurityEnforcerAdaptor
    - DockerAdaptor
  cleanup:
    - DockerAdaptor
    - SecurityEnforcerAdaptor


adaptor_config:
 SecurityEnforcerAdaptor:
   types:
     - "tosca.policies.DockerSecretDistribution"
   endpoint: "http://127.0.0.1:5001/v1.0"
#   volume: "/Users/greg/Desktop/work/COLA/submitter/greg_fork/component_submitter/files/output_configs/"
   volume: "/var/lib/micado/toscasubmitter/src/"

 DockerAdaptor:
   types:
     - "tosca.nodes.MiCADO.Container.Application.Docker"
#   volume: "/Users/greg/Desktop/work/COLA/submitter/greg_fork/component_submitter/files/output_configs/"
