main_config:
  dry_run: True
  path_log: "/var/lib/submitter/submitter.log"

step:
  translate:
    - SecurityEnforcerAdaptor
    - DockerAdaptor
  execute:
    - DockerAdaptor
    - SecurityEnforcerAdaptor
  update:
    - DockerAdaptor
    - SecurityEnforcerAdaptor
  undeploy:
    - SecurityEnforcerAdaptor
    - DockerAdaptor
  cleanup:
    - DockerAdaptor
    - SecurityEnforcerAdaptor


adaptor_config:
 SecurityEnforcerAdaptor:
   types:
     - "tosca.policies.DockerSecretDistribution"
   endpoint: "http://127.0.0.1:5001/v1.0"


 DockerAdaptor:
   types:
     - "tosca.nodes.MiCADO.Container.Application.Docker"
   volume: "/var/lib/submitter/files/output_configs/"
