key_config:
  DummySeAdaptor:
    - "tosca.nodes.MiCADO.Container.Application.Docker"
  ScalingPolicyAdaptor:
    - "tosca.nodes.MiCADO.Container.Application.Docker"

  DockerAdaptor:
    #DockerAdaptor
    - "tosca.nodes.MiCADO.Container.Application.Docker"
#  cloud_orchestrator:
#    - "tosca.nodes.MiCADO.*"
#    - "tosca.nodes.MiCADO.Occopus.CloudSigma.Compute"
#    - "tosca.nodes.MiCADO.Occopus.Nova.Compute"
#    - "tosca.nodes.MiCADO.Occopus.CloudBroker.Compute"
#    - "tosca.nodes.MiCADO.Occopus.EC2.Compute"

#  policies_engine:
#    - "tosca.nodes.MiCADO.*"
#    - "tosca.nodes.MiCADO.Container.Application.Docker"
#  security_enforcer:
#    - "some security Enforcer"
