config:
  dry_run: False
  path_log: "/var/lib/submitter/submitter.log"

step:
  translate:
    - SecurityEnforcerAdaptor
    - DockerAdaptor
  execute:
    - DockerAdaptor
    - SecurityEnforcerAdaptor
  update:
    - DockerAdaptor
    - SecurityEnforcerAdaptor
  undeploy:
    - SecurityEnforcerAdaptor
    - DockerAdaptor
  cleanup:
    - DockerAdaptor
    - SecurityEnforcerAdaptor


adaptor_config:
 SecurityEnforcerAdaptor:
   types:
     - "tosca.policies.Scaling.*"
   endoint: "endpoint"
   volume: "/var/lib/submitter/security_workdir_example/"


 DockerAdaptor:
   types:
     - "tosca.nodes.MiCADO.Container.Application.Docker"
   endoint: "endpoint"
   volume: "/var/lib/submitter/files/output_configs/"
