config:
  dry_run: True
  path_log: "/Users/greg/Desktop/work/COLA/submitter/greg_fork/component_submitter/submitter.log"

Adaptor_config:
 SecurityEnforcerAdaptor:
   types:
     - "tosca.policies.DockerSecretDistribution"
   endpoint: "http://127.0.0.1:5001/v1.0"
   volume: "/Users/greg/Desktop/work/COLA/submitter/greg_fork/component_submitter/files/output_configs/"


 DockerAdaptor:
   types:
     - "tosca.nodes.MiCADO.Container.Application.Docker"
   endpoint: "endpoint"
   volume: "/Users/greg/Desktop/work/COLA/submitter/greg_fork/component_submitter/files/output_configs/"
