config:
  dry_run: True
  path_log: "/Users/greg/Desktop/work/COLA/submitter/greg_fork/component_submitter/submitter.log"
  volume: "/Users/greg/Desktop/work/COLA/submitter/greg_fork/component_submitter/files/output_configs/"

Adaptor_config:
 DummySeAdaptor:
   types:
     - "tosca.policies.Scaling.*"
   endoint: "endpoint"


 DockerAdaptor:
   types:
     - "tosca.nodes.MiCADO.Container.Application.Docker"
   endoint: "endpoint"
